### ISSUE TITLE
Loading effects from amp or file does not preserve the position

### ISSUE THREAD

**Issue by j824h** [offa/plug#13]
## Loading from a Mustang amp
**In `decodeEffectsFromData()`, effects in `Position::input` and `Position::effectsLoop` collide.**

https://github.com/offa/plug/blob/8d93d21ab26107442a144851e5074871b4dd3478/src/com/PacketSerializer.cpp#L182-L183
When two effects are in a same _slot number_(=POS%4), each of `Position::input` and `Position::effectsLoop`, the one in the later packet (in the order of stompbox, modulation, delay, reverb) will erase the other.

This occurs possibly in the preset created with Fender Fuse, and so in the built-in V2 presets "Amin 3rds Solo", "Angry Rodent", "Purple Fuzz" (maybe different POS value from V1's?).
Those are treated as  valid presets when loaded at Mustang I V2.

## Loading from a file
In `parseFX()`, `fx_slot` is reset as its rank.
This will effectively make a preset safe for `decodeEffectsFromData()`, but at the loss of exact user-defined position.

https://github.com/offa/plug/blob/8d93d21ab26107442a144851e5074871b4dd3478/src/ui/loadfromfile.cpp#L221-L232
https://github.com/offa/plug/blob/8d93d21ab26107442a144851e5074871b4dd3478/src/ui/loadfromfile.cpp#L424-L429

**Comment by j824h** [comment]
## Note on the vendor's design

An effect setting contains the position parameter ("POS" in the .fuse XML), ranging from 0 to 7.
The value encodes the order how the effect should be chained with other effect or the amplifier simulation.
The range is divided into 0-3, 4-7 so that amplifier simulation can be set between 2 groups of 4 effect slots.
The maximum number of effects used is 4 (when choosing one from all of the 4 types), so each group has sufficient slots to contain all used effects.

For the most natural representation, the interface should expose 8 slots.
This will generally give redundancy even when the maximum number of effects is used.

On the other hand, `plug` chose to use `fx_pedal_settings::fx_slot` ranging from 0 to 3, and `fx_pedal_settings::position` ranging from 0 to 1.

**Comment by offa** [comment]
I don't know what's the thought behind the current behaviour, but we should consider the vendors design instead.

So let's think about what needs to be changed:

- UI: 4 pre and 4 post amp slots (8 in total)
- Slot value: Use 0-3 for pre and 4-7 for post amp
- Change load-from-file accordingly
- Remove `Position` enum since it's no longer needed
- :question: is `fx_pedal_settings.position` still necessary?

**Comment by offa** [comment]
While working on this, I've noticed many arrays of 4 effects which may need further investigation.

**Comment by offa** [comment]
Most parts of core slot changes are done; pre / post effects are handled differently now. You can get a _work-in-progress_ version from [Gitlab](https://gitlab.com/offa/plug) ([`245-fx_slots`](https://gitlab.com/offa/plug/-/commits/245-fx_slots) branch). 

The progress is tracked in the [related issue](https://gitlab.com/offa/plug/-/issues/245) there (commenting here is still fine though :wink:).

While the UI should handle slots correctly now, there are still some changes needed. Especially any file related operations need some more work and are likely broken at the moment – so please create backups before testing.

Good change to get rid of some technical dept btw..

**Comment by offa** [comment]
I have merged first iteration into master. Slots of 1-8 are used now.

**Comment by offa** [comment]
@j824h can you test whether order is preserved now?

**Comment by j824h** [comment]
The order seems to be preserved, both when loading from a Mustang amp and loading from a file.

What breaks are the effect parameters, when loading from a file.
Every effect parameter seems to be set as 0 (default constructor?).

Another minor issue occuring in cb2bf2cfcd3d9e52d1b8e416a2840f39e22d37a5 is that
1. F5, F6, F7, F8 shortcuts to toggle FX(5, 6, 7, 8) are not functioning, when the window for the corresponding FX(1, 2, 3, 4) is open,
2. (MacOS Qt specific) In the main window, the row of QPushButton: FxEffectButton(1, 2, 3, 4) looks inconsistent to EffectButton(1, 2, 3, 4) or Amplifier. The difference should come from whether minimumSize is set consistently. 
(https://doc.qt.io/qt-5/qpushbutton.html#:~:text=Note%3A%20On%20macOS)

Do you think those deserve their own issues, or just belong to this one as relating to 4 -> 8?

**Comment by offa** [comment]
Thanks for your feedback.

> What breaks are the effect parameters, when loading from a file.
Every effect parameter seems to be set as 0 (default constructor?).

The loading logic is really wired at some places, I'll have a look at it. (Stupid question, I know) This was working with the old IDs?

> (MacOS Qt specific) In the main window, the row of QPushButton: FxEffectButton(1, 2, 3, 4) looks inconsistent to EffectButton(1, 2, 3, 4) or Amplifier. The difference should come from whether minimumSize is set consistently.
(https://doc.qt.io/qt-5/qpushbutton.html#:~:text=Note%3A%20On%20macOS)

I do not have a system to reproduce this, so I might need your testing

> Do you think those deserve their own issues, or just belong to this one as relating to 4 -> 8?

I'm fine with both. We can create separate issues at any time :-)

**Comment by offa** [comment]
Regarding Mac OS buttons: Could you have a look at `266-osx_buttons` branch? I have changed the FX loop buttons to same minimum size as the others. And increased minimum height to 30 as mentioned in the docs.

**Comment by j824h** [comment]
> Regarding Mac OS buttons: Could you have a look at `266-osx_buttons` branch? I have changed the FX loop buttons to same minimum size as the others. And increased minimum height to 30 as mentioned in the docs.

Now I like that every button for effects is consistently round-shaped in the default window size.
<img width="416" alt="Screenshot 2022-10-28 at 11 49 46" src="https://user-images.githubusercontent.com/10954732/198481172-59fcf67c-a413-4afe-91d5-c1cf92a854fe.png">
When the window is resized though, `hsizetype="Expanding"` will bring the old situation back.
<img width="416" alt="Screenshot 2022-10-28 at 11 50 31" src="https://user-images.githubusercontent.com/10954732/198484122-9710df50-25c6-4904-aa57-b4b7e57cd9b8.png">
Even if the stable consistency is what we can agree on, it seems the fix will depend on aesthetic decisions.
So let's put this outside of this issue...

**Comment by offa** [comment]
> Even if the stable consistency is what we can agree on, it seems the fix will depend on aesthetic decisions.
So let's put this out of this issue and for later debate...

I'd expect it should stay consistent over all sizes. Or is this style change common on Mac applications (I wouldn't expect)?

What I tried to get are all buttons square … seems we need another iteration here.


What's strange to me: The corners become square with increased size, but accoring to docs it should be oppsoiste:

> Note: On macOS when a push button's width becomes smaller than 50 or its height becomes smaller than 30, the button's corners are changed from round to square. Use the setMinimumSize() function to prevent this behavior.

**Comment by offa** [comment]
Next iteration: I have updated the branch to use same size policy for FX buttons.

**Comment by offa** [comment]
I have fixed broken shortcut slot connections on `master` can you reproduce the problem with that version?

**Comment by j824h** [comment]
The issue seems persisting. For example, F5 works when FX1 window is off, but doesn't seem to do anything when FX1 window is on.

**Comment by offa** [comment]
I have tried to reproduce it with these steps:

1. Open Plug with Effect #1 and Effect #5 empty
1. Press Ctrl+1 --> Effect #1 window opens and active
1. Press Ctrl+5 --> Effect #5 window opens and active
1. Close #5 Window and Press Ctrl+5 --> Effect #5 window opens again
1. Close both
1. Press Ctrl+5 --> Effect #5 window opens
1. Press Ctrl+1 and set "off"
1. Press Ctrl+5 --> Effect #5 window opens
1. Press Ctrl+1 and set "on"
1. Press Ctrl+5 --> Effect #5 window opens
1. Pressing either Ctrl+1 or Ctrl+5 show their corresponding windows

Everything works as expected though. Where does it stop working when you the steps?

**Comment by j824h** [comment]
You mean Ctrl + n? I meant Fn.

**Comment by offa** [comment]
The shortcuts are mapped as Ctrl key and a number. According to [qt docs](https://doc.qt.io/qt-5/qt.html#Modifier-enum) things are a little different on OS X, which uses different modifiers.

**Comment by j824h** [comment]
> I have tried to reproduce it with these steps:
> 
> 1. Open Plug with Effect 1 and Effect 5 empty
> 2. Press Ctrl+1 --> Effect 1 window opens and active
> 3. Press Ctrl+5 --> Effect 5 window opens and active
> 4. Close 5 Window and Press Ctrl+5 --> Effect 5 window opens again
> 5. Close both
> 6. Press Ctrl+5 --> Effect 5 window opens
> 7. Press Ctrl+1 and set "off"
> 8. Press Ctrl+5 --> Effect 5 window opens
> 9. Press Ctrl+1 and set "on"
> 10. Press Ctrl+5 --> Effect 5 window opens
> 11. Pressing either Ctrl+1 or Ctrl+5 show their corresponding windows
> 
> Everything works as expected though. Where does it stop working when you the steps?

I'm sorry that I might have confused you, but I really meant Fn.

https://github.com/offa/plug/blob/a38ded4544229785e1fc58abdede672ce347f497/src/ui/effect.cpp#L135

I somehow have discovered the shortcuts, they worked for F1–F4, and now I see where they come from + why they don't work any more.
I thought we should be supporting this.
What do you think?

**Comment by offa** [comment]
I see! Indeed, I can reproduce this.

From a first look: The new slot numbering has introduced conflicting shortcuts.

- Toggles: F1 to F8
- Defaulting: F5 to F12 (= slot + 5)

Now, usually there aren't enough F-Keys to map both, so we have to change the mapping.

How about leaving toggle on the F-keys (used more often?) and change 'load default' to Ctrl + F-Key?

**Comment by offa** [comment]
The shortcuts are as listed above now – the issue should be fixed now :-).

**Comment by offa** [comment]
@j824h what's still open here?

**Comment by j824h** [comment]
F1 to F8 work correctly.

Button shape issue doesn't seem fixed though, basically same as in https://github.com/offa/plug/issues/13#issuecomment-1294387127.
I hope I can look into your attempted fix, but that might be possible some other days later.

**Comment by j824h** [comment]
I had not applied 628ffeab09bfc6398782d56324f1c1198477b3d6 and have been wondering why nothing changed. With the fix:
<img width="416" alt="Screenshot 2023-04-23 at 9 52 27" src="https://user-images.githubusercontent.com/10954732/233813714-896f5a0d-3902-4033-b248-e738bd12f7ad.png">
I guess this should look good enough.
