### ISSUE TITLE
Fedora 36 FTBFS due to warnings as error - Allow?

### ISSUE THREAD

**Issue by kathenas** [offa/plug#16]
Fedora 36 FTBFS due to warnings as error - Allow?

`[ 98%] Linking CXX executable MustangTest
cd /builddir/build/BUILD/plug-1.4.3/redhat-linux-build/test && /usr/bin/cmake -E cmake_link_script CMakeFiles/MustangTest.dir/link.txt --verbose=1
/usr/bin/g++ -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -Wl,-dT,/builddir/build/BUILD/plug-1.4.3/.package_note-plug-1.4.3-1.fc36.x86_64.ld CMakeFiles/MustangTest.dir/MustangTest.cpp.o CMakeFiles/MustangTest.dir/PacketSerializerTest.cpp.o CMakeFiles/MustangTest.dir/PacketTest.cpp.o -o MustangTest  ../src/com/libplug-mustang.a ../src/com/libplug-communication.a mocks/libLibUsbMocks.a /usr/lib64/libgtest.so /usr/lib64/libgmock.so /usr/lib64/libgtest_main.so 
In file included from /usr/include/gtest/internal/gtest-death-test-internal.h:39,
                 from /usr/include/gtest/gtest-death-test.h:41,
                 from /usr/include/gtest/gtest.h:64,
                 from /usr/include/gmock/internal/gmock-internal-utils.h:47,
                 from /usr/include/gmock/gmock-actions.h:145,
                 from /usr/include/gmock/gmock.h:59,
                 from /builddir/build/BUILD/plug-1.4.3/test/mocks/LibUsbMocks.h:23,
                 from /builddir/build/BUILD/plug-1.4.3/test/UsbTest.cpp:23:
In member function 'testing::internal::MatcherBase<libusb_context**>::MatcherBase(testing::internal::MatcherBase<libusb_context**> const&)',
    inlined from 'testing::Matcher<libusb_context**>::Matcher(testing::Matcher<libusb_context**> const&)' at /usr/include/gtest/gtest-matchers.h:479:7,
    inlined from 'mock::UsbMock::gmock_init(testing::Matcher<libusb_context**> const&)' at /builddir/build/BUILD/plug-1.4.3/test/mocks/LibUsbMocks.h:31:9,
    inlined from 'UsbTest_contextDtorDeinitializesDefaultContext_Test::TestBody()' at /builddir/build/BUILD/plug-1.4.3/test/UsbTest.cpp:76:5:
/usr/include/gtest/gtest-matchers.h:302:33: error: 'MEM[(const struct MatcherBase &)&D.234397].buffer_' may be used uninitialized [-Werror=maybe-uninitialized]
  302 |       : vtable_(other.vtable_), buffer_(other.buffer_) {
      |                                 ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gmock/gmock-function-mocker.h:42,
                 from /usr/include/gmock/gmock.h:61:
/builddir/build/BUILD/plug-1.4.3/test/UsbTest.cpp: In member function 'UsbTest_contextDtorDeinitializesDefaultContext_Test::TestBody()':
/builddir/build/BUILD/plug-1.4.3/test/UsbTest.cpp:76:31: note: '<anonymous>' declared here
   76 |     EXPECT_CALL(*usbmock, init(_)).WillOnce(Return(LIBUSB_SUCCESS));
      |                               ^
In member function 'testing::internal::MatcherBase<libusb_context*>::MatcherBase(testing::internal::MatcherBase<libusb_context*> const&)',
    inlined from 'testing::Matcher<libusb_context*>::Matcher(testing::Matcher<libusb_context*> const&)' at /usr/include/gtest/gtest-matchers.h:479:7,
    inlined from 'mock::UsbMock::gmock_exit(testing::Matcher<libusb_context*> const&)' at /builddir/build/BUILD/plug-1.4.3/test/mocks/LibUsbMocks.h:34:9,
    inlined from 'UsbTest_contextCtorInitializesDefaultContext_Test::TestBody()' at /builddir/build/BUILD/plug-1.4.3/test/UsbTest.cpp:60:5:
/usr/include/gtest/gtest-matchers.h:302:33: error: 'MEM[(const struct MatcherBase &)&D.231013].buffer_' may be used uninitialized [-Werror=maybe-uninitialized]
  302 |       : vtable_(other.vtable_), buffer_(other.buffer_) {
      |                                 ^~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/plug-1.4.3/test/UsbTest.cpp: In member function 'UsbTest_contextCtorInitializesDefaultContext_Test::TestBody()':
/builddir/build/BUILD/plug-1.4.3/test/UsbTest.cpp:60:31: note: '<anonymous>' declared here
   60 |     EXPECT_CALL(*usbmock, exit(_));
      |                               ^
gmake[2]: Leaving directory '/builddir/build/BUILD/plug-1.4.3/redhat-linux-build'
[ 98%] Built target MustangTest
cc1plus: all warnings being treated as errors
gmake[2]: Leaving directory '/builddir/build/BUILD/plug-1.4.3/redhat-linux-build'
gmake[2]: *** [test/CMakeFiles/UsbTest.dir/build.make:79: test/CMakeFiles/UsbTest.dir/UsbTest.cpp.o] Error 1
gmake[1]: Leaving directory '/builddir/build/BUILD/plug-1.4.3/redhat-linux-build'
gmake[1]: *** [CMakeFiles/Makefile2:487: test/CMakeFiles/UsbTest.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.ZZtdqK (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.ZZtdqK (%build)
Finish: rpmbuild plug-1.4.3-1.el8.src.rpm
Finish: build phase for plug-1.4.3-1.el8.src.rpm
ERROR: Exception(SRPMS/plug-1.4.3-1.el8.src.rpm) Config(fedora-36-x86_64) 1 minutes 13 seconds
INFO: Results and/or logs in: /var/lib/mock/fedora-36-x86_64/result

**Comment by kathenas** [comment]
> Thanks for reporting. What version of GTest are you using? If I remember correctly the issue was fixed with Gtest 1.12.x release.

Thanks for the info. Chain building latest gtest 1.12.1 then latest plug results in a  successful build. I have requested gtest be updated in Fedora 36 and will close this issue,

**Comment by offa** [comment]
Great, let me know if you experience further issues. :+1:
