### ISSUE TITLE
What it is for?

### ISSUE THREAD

**Issue by 6801318d8d** [offa/plug#27]
I have read the README but it doesn't document at all why I would need this software.

I have a Fender Mustang Micro.

Why I need this software?

**Comment by offa** [comment]
Whether you need it or not fully depends on you :-).

**Comment by 6801318d8d** [comment]
Well, rephrasing ... what does this software do? Am I supposed to find out by myself?

**Comment by 6801318d8d** [comment]
The only thing we know from project description is that it is a software "for Fender Mustang Amps". Do I install it inside the amp? Or is this a sort of driver?

**Comment by offa** [comment]
It's more or less an alternative to the FUSE client software. I have added that info the readme.

Is your question answered?

**Comment by 6801318d8d** [comment]
FUSA as in Filesystem in Userspace? So I can map the SSD of the amplifier in a filesystem?

**Comment by offa** [comment]
FUSE as the Fender FUSE software.

**Comment by 6801318d8d** [comment]
So this is a software to create and modify presets of digital amplifiers?

**Comment by offa** [comment]
Yes, you could say that.

**Comment by 6801318d8d** [comment]
That was a good description of your software for me, wasn't it? ;)

**Comment by 6801318d8d** [comment]
I guess it wouldn't work with the Mustang Micro Plus though?

**Comment by offa** [comment]
> I guess it wouldn't work with the Mustang Micro Plus though?

This depends on the protocol used; if it uses the Mustang protocol it might work, but newer devices use something different.

**Comment by 6801318d8d** [comment]
ok thanks
