### ISSUE TITLE
Could NOT find GTest

### ISSUE THREAD

**Issue by lucky62** [offa/plug#4]
cmake ends with error. What is missing?

$ cmake ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ~~~ plug v1.4.1 ~~~
-- Unit Tests : ON
-- Integrationtests : OFF
-- Coverage : OFF
-- LTO : OFF
-- ASan : OFF
-- UBSan : OFF
-- Build Type : None
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found libusb-1.0: /usr/lib/x86_64-linux-gnu/libusb-1.0.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find GTest (missing: GTest_INCLUDE_DIR GTest_Mock_INCLUDE_DIR
  GTest_LIBRARY GTest_Mock_LIBRARY GTest_Main_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGTest.cmake:33 (find_package_handle_standard_args)
  test/CMakeLists.txt:1 (find_package)

-- Configuring incomplete, errors occurred!
See also "/SHARED/SSD_DATA/plug/build/CMakeFiles/CMakeOutput.log".
See also "/SHARED/SSD_DATA/plug/build/CMakeFiles/CMakeError.log".

**Comment by lucky62** [comment]
I am on Linux Mint 20.
Installation of libgtest-dev & googletest was not helpful.

**Comment by lucky62** [comment]
Thanks for the response.

Some search results...

Packages searched by keywords **gtest**

> `$ apt-cache search gtest`
autopkgtest - automatic as-installed testing for Debian packages
caffe-tools-cpu - Tools for fast, open framework for Deep Learning (CPU_ONLY)
cct-examples - example data for testing the package cct
cmake-extras - Extra CMake utility modules
debian-policy - Debian Policy Manual and related documents
dh-octave-autopkgtest - script for the automatic testing of Octave add-on packages
flatpak-xdg-utils-tests - as-installed tests for flatpak-xdg-utils
gnome-desktop-testing - runner for GNOME installed tests
grubzfs-testsuite - Testsuite for grub menu generation on zfs systems
kallisto-examples - near-optimal RNA-Seq quantification (example data)
kleborate-examples - tool to screen Klebsiella genome assemblies (example data)
libdist-zilla-plugin-podspellingtests-perl - Backward-compatibility wrapper around Dist::Zilla::Plugin::Test::PodSpelling
libdist-zilla-plugin-test-podspelling-perl - Author tests for POD spelling
libgcab-tests - Microsoft Cabinet file manipulation library - as-installed tests
**libgtest-dev** - Google's framework for writing C++ tests
libsoup2.4-tests - HTTP library implementation in C -- installed tests
libxorg-gtest-data - X.Org dummy testing environment for Google Test - data
libxorg-gtest-dev - X.Org dummy testing environment for Google Test - headers
libxorg-gtest-doc - X.org dummy testing environment for Google Test - documentation
openssh-tests - OpenSSH regression tests
parsinsert-testdata - Test data for parsinsert
pkg-js-autopkgtest - collection of autopktest scripts for Nodejs packages
pkg-perl-autopkgtest - collection of autopktest scripts for Perl packages
pkg-r-autopkgtest - Script for the automatic testing of R packages
python3-nose-timer - timer plugin for nosetests - Python 3.x
systemd-tests - tests for systemd
xdg-dbus-proxy-tests - filtering D-Bus proxy - as-installed tests

Packages searched by keyword **gmock**:

> $ apt-cache search gmock
cmake-extras - Extra CMake utility modules
**google-mock** - Google's framework for writing and using C++ mock classes
**libgmock-dev** - Google's framework for writing C++ tests

Packages searched by keyword **google** - filtered by **test**:

> `$ apt-cache search google | grep test`
golang-github-dylanmei-winrmtest-dev - testing addon for golang-github-masterzen-winrm
golang-github-google-go-cmp-dev - Package for comparing Go values in tests
golang-github-google-gofuzz-dev - Fuzz testing for Go
golang-github-jacobsa-oglematchers-dev - matchers for testing/mocking frameworks such as ogletest
golang-github-jacobsa-ogletest-dev - unit testing framework for Go
**googletest** - Google's C++ test framework sources
**googletest-tools** - Google's C++ test framework sources
libgdata-tests - Library for accessing GData webservices - common data files
**libgmock-dev** - Google's framework for writing C++ tests
**libgtest-dev** - Google's framework for writing C++ tests
libxorg-gtest-data - X.Org dummy testing environment for Google Test - data
libxorg-gtest-dev - X.Org dummy testing environment for Google Test - headers
libxorg-gtest-doc - X.org dummy testing environment for Google Test - documentation

Packages searched by keyword **google** - filtered by **mock**:

> `$ apt-cache search google | grep mock`
dummydroid - Register a GSF ID for mock-up Android devices
golang-github-jacobsa-oglematchers-dev - matchers for testing/mocking frameworks such as ogletest
golang-github-jacobsa-oglemock-dev - mocking framework for Go
**google-mock** - Google's framework for writing and using C++ mock classes
**libgmock-de**v - Google's framework for writing C++ tests

Will try to install some of highlighted packages...

**Comment by offa** [comment]
Please also check what files are actually provided by the packages.

**Comment by lucky62** [comment]
all highlighted packages installed - problem still exists.

PLUG compiled successfully with UNITTEST=OFF.

**Comment by offa** [comment]
What files are provided by packages?

**Comment by lucky62** [comment]
files in package **libgtest-dev**:

> /.
/usr
/usr/include
/usr/include/gtest
/usr/include/gtest/gtest-death-test.h
/usr/include/gtest/gtest-matchers.h
/usr/include/gtest/gtest-message.h
/usr/include/gtest/gtest-param-test.h
/usr/include/gtest/gtest-printers.h
/usr/include/gtest/gtest-spi.h
/usr/include/gtest/gtest-test-part.h
/usr/include/gtest/gtest-typed-test.h
/usr/include/gtest/gtest.h
/usr/include/gtest/gtest_pred_impl.h
/usr/include/gtest/gtest_prod.h
/usr/include/gtest/internal
/usr/include/gtest/internal/custom
/usr/include/gtest/internal/custom/README.md
/usr/include/gtest/internal/custom/gtest-port.h
/usr/include/gtest/internal/custom/gtest-printers.h
/usr/include/gtest/internal/custom/gtest.h
/usr/include/gtest/internal/gtest-death-test-internal.h
/usr/include/gtest/internal/gtest-filepath.h
/usr/include/gtest/internal/gtest-internal.h
/usr/include/gtest/internal/gtest-param-util.h
/usr/include/gtest/internal/gtest-port-arch.h
/usr/include/gtest/internal/gtest-port.h
/usr/include/gtest/internal/gtest-string.h
/usr/include/gtest/internal/gtest-type-util.h
/usr/include/gtest/internal/gtest-type-util.h.pump
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libgtest.a
/usr/lib/x86_64-linux-gnu/libgtest_main.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/gtest.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gtest_main.pc
/usr/share
/usr/share/doc
/usr/share/doc/libgtest-dev
/usr/share/doc/libgtest-dev/changelog.Debian.gz
/usr/share/doc/libgtest-dev/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/libgtest-dev
/usr/src
/usr/src/gtest

files in package **libgmock-dev**:
>/.
/usr
/usr/include
/usr/include/gmock
/usr/include/gmock/gmock-actions.h
/usr/include/gmock/gmock-cardinalities.h
/usr/include/gmock/gmock-function-mocker.h
/usr/include/gmock/gmock-generated-actions.h
/usr/include/gmock/gmock-generated-actions.h.pump
/usr/include/gmock/gmock-generated-function-mockers.h
/usr/include/gmock/gmock-generated-function-mockers.h.pump
/usr/include/gmock/gmock-generated-matchers.h
/usr/include/gmock/gmock-generated-matchers.h.pump
/usr/include/gmock/gmock-matchers.h
/usr/include/gmock/gmock-more-actions.h
/usr/include/gmock/gmock-more-matchers.h
/usr/include/gmock/gmock-nice-strict.h
/usr/include/gmock/gmock-spec-builders.h
/usr/include/gmock/gmock.h
/usr/include/gmock/internal
/usr/include/gmock/internal/custom
/usr/include/gmock/internal/custom/README.md
/usr/include/gmock/internal/custom/gmock-generated-actions.h
/usr/include/gmock/internal/custom/gmock-generated-actions.h.pump
/usr/include/gmock/internal/custom/gmock-matchers.h
/usr/include/gmock/internal/custom/gmock-port.h
/usr/include/gmock/internal/gmock-internal-utils.h
/usr/include/gmock/internal/gmock-port.h
/usr/include/gmock/internal/gmock-pp.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libgmock.a
/usr/lib/x86_64-linux-gnu/libgmock_main.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/gmock.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/gmock_main.pc
/usr/share
/usr/share/doc
/usr/share/doc/libgmock-dev
/usr/share/doc/libgmock-dev/changelog.Debian.gz
/usr/share/doc/libgmock-dev/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/libgmock-dev

files in package **googletest**:
>/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/googletest
/usr/share/doc/googletest/README.Debian
/usr/share/doc/googletest/README.md.gz
/usr/share/doc/googletest/changelog.Debian.gz
/usr/share/doc/googletest/copyright
/usr/src
/usr/src/googletest
/usr/src/googletest/CMakeLists.txt
/usr/src/googletest/googlemock
/usr/src/googletest/googlemock/CMakeLists.txt
/usr/src/googletest/googlemock/CONTRIBUTORS
/usr/src/googletest/googlemock/LICENSE
/usr/src/googletest/googlemock/README.md
/usr/src/googletest/googlemock/cmake
/usr/src/googletest/googlemock/cmake/gmock.pc.in
/usr/src/googletest/googlemock/cmake/gmock_main.pc.in
/usr/src/googletest/googlemock/docs
/usr/src/googletest/googlemock/docs/cheat_sheet.md
/usr/src/googletest/googlemock/docs/cook_book.md
/usr/src/googletest/googlemock/docs/for_dummies.md
/usr/src/googletest/googlemock/docs/gmock_faq.md
/usr/src/googletest/googlemock/include
/usr/src/googletest/googlemock/include/gmock
/usr/src/googletest/googlemock/include/gmock/gmock-actions.h
/usr/src/googletest/googlemock/include/gmock/gmock-cardinalities.h
/usr/src/googletest/googlemock/include/gmock/gmock-function-mocker.h
/usr/src/googletest/googlemock/include/gmock/gmock-generated-actions.h
/usr/src/googletest/googlemock/include/gmock/gmock-generated-actions.h.pump
/usr/src/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h
/usr/src/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h.pump
/usr/src/googletest/googlemock/include/gmock/gmock-generated-matchers.h
/usr/src/googletest/googlemock/include/gmock/gmock-generated-matchers.h.pump
/usr/src/googletest/googlemock/include/gmock/gmock-matchers.h
/usr/src/googletest/googlemock/include/gmock/gmock-more-actions.h
/usr/src/googletest/googlemock/include/gmock/gmock-more-matchers.h
/usr/src/googletest/googlemock/include/gmock/gmock-nice-strict.h
/usr/src/googletest/googlemock/include/gmock/gmock-spec-builders.h
/usr/src/googletest/googlemock/include/gmock/gmock.h
/usr/src/googletest/googlemock/include/gmock/internal
/usr/src/googletest/googlemock/include/gmock/internal/custom
/usr/src/googletest/googlemock/include/gmock/internal/custom/README.md
/usr/src/googletest/googlemock/include/gmock/internal/custom/gmock-generated-actions.h
/usr/src/googletest/googlemock/include/gmock/internal/custom/gmock-generated-actions.h.pump
/usr/src/googletest/googlemock/include/gmock/internal/custom/gmock-matchers.h
/usr/src/googletest/googlemock/include/gmock/internal/custom/gmock-port.h
/usr/src/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h
/usr/src/googletest/googlemock/include/gmock/internal/gmock-port.h
/usr/src/googletest/googlemock/include/gmock/internal/gmock-pp.h
/usr/src/googletest/googlemock/scripts
/usr/src/googletest/googlemock/scripts/fuse_gmock_files.py
/usr/src/googletest/googlemock/scripts/generator
/usr/src/googletest/googlemock/scripts/generator/LICENSE
/usr/src/googletest/googlemock/scripts/generator/README
/usr/src/googletest/googlemock/scripts/generator/README.cppclean
/usr/src/googletest/googlemock/scripts/generator/cpp
/usr/src/googletest/googlemock/scripts/generator/cpp/__init__.py
/usr/src/googletest/googlemock/scripts/generator/cpp/ast.py
/usr/src/googletest/googlemock/scripts/generator/cpp/gmock_class.py
/usr/src/googletest/googlemock/scripts/generator/cpp/gmock_class_test.py
/usr/src/googletest/googlemock/scripts/generator/cpp/keywords.py
/usr/src/googletest/googlemock/scripts/generator/cpp/tokenize.py
/usr/src/googletest/googlemock/scripts/generator/cpp/utils.py
/usr/src/googletest/googlemock/scripts/generator/gmock_gen
/usr/src/googletest/googlemock/scripts/generator/gmock_gen.py
/usr/src/googletest/googlemock/scripts/gmock-config.in
/usr/src/googletest/googlemock/scripts/gmock_doctor.py
/usr/src/googletest/googlemock/scripts/upload.py
/usr/src/googletest/googlemock/scripts/upload_gmock.py
/usr/src/googletest/googlemock/src
/usr/src/googletest/googlemock/src/gmock-all.cc
/usr/src/googletest/googlemock/src/gmock-cardinalities.cc
/usr/src/googletest/googlemock/src/gmock-internal-utils.cc
/usr/src/googletest/googlemock/src/gmock-matchers.cc
/usr/src/googletest/googlemock/src/gmock-spec-builders.cc
/usr/src/googletest/googlemock/src/gmock.cc
/usr/src/googletest/googlemock/src/gmock_main.cc
/usr/src/googletest/googlemock/test
/usr/src/googletest/googlemock/test/BUILD.bazel
/usr/src/googletest/googlemock/test/gmock-actions_test.cc
/usr/src/googletest/googlemock/test/gmock-cardinalities_test.cc
/usr/src/googletest/googlemock/test/gmock-function-mocker_nc.cc
/usr/src/googletest/googlemock/test/gmock-function-mocker_nc_test.py
/usr/src/googletest/googlemock/test/gmock-function-mocker_test.cc
/usr/src/googletest/googlemock/test/gmock-generated-actions_test.cc
/usr/src/googletest/googlemock/test/gmock-generated-function-mockers_test.cc
/usr/src/googletest/googlemock/test/gmock-generated-matchers_test.cc
/usr/src/googletest/googlemock/test/gmock-internal-utils_test.cc
/usr/src/googletest/googlemock/test/gmock-matchers_test.cc
/usr/src/googletest/googlemock/test/gmock-more-actions_test.cc
/usr/src/googletest/googlemock/test/gmock-nice-strict_test.cc
/usr/src/googletest/googlemock/test/gmock-port_test.cc
/usr/src/googletest/googlemock/test/gmock-pp-string_test.cc
/usr/src/googletest/googlemock/test/gmock-pp_test.cc
/usr/src/googletest/googlemock/test/gmock-spec-builders_test.cc
/usr/src/googletest/googlemock/test/gmock_all_test.cc
/usr/src/googletest/googlemock/test/gmock_ex_test.cc
/usr/src/googletest/googlemock/test/gmock_leak_test.py
/usr/src/googletest/googlemock/test/gmock_leak_test_.cc
/usr/src/googletest/googlemock/test/gmock_link2_test.cc
/usr/src/googletest/googlemock/test/gmock_link_test.cc
/usr/src/googletest/googlemock/test/gmock_link_test.h
/usr/src/googletest/googlemock/test/gmock_output_test.py
/usr/src/googletest/googlemock/test/gmock_output_test_.cc
/usr/src/googletest/googlemock/test/gmock_output_test_golden.txt
/usr/src/googletest/googlemock/test/gmock_stress_test.cc
/usr/src/googletest/googlemock/test/gmock_test.cc
/usr/src/googletest/googlemock/test/gmock_test_utils.py
/usr/src/googletest/googletest
/usr/src/googletest/googletest/CMakeLists.txt
/usr/src/googletest/googletest/CONTRIBUTORS
/usr/src/googletest/googletest/README.md
/usr/src/googletest/googletest/cmake
/usr/src/googletest/googletest/cmake/Config.cmake.in
/usr/src/googletest/googletest/cmake/gtest.pc.in
/usr/src/googletest/googletest/cmake/gtest_main.pc.in
/usr/src/googletest/googletest/cmake/internal_utils.cmake
/usr/src/googletest/googletest/cmake/libgtest.la.in
/usr/src/googletest/googletest/docs
/usr/src/googletest/googletest/docs/advanced.md
/usr/src/googletest/googletest/docs/faq.md
/usr/src/googletest/googletest/docs/pkgconfig.md
/usr/src/googletest/googletest/docs/primer.md
/usr/src/googletest/googletest/docs/pump_manual.md
/usr/src/googletest/googletest/docs/samples.md
/usr/src/googletest/googletest/include
/usr/src/googletest/googletest/include/gtest
/usr/src/googletest/googletest/include/gtest/gtest-death-test.h
/usr/src/googletest/googletest/include/gtest/gtest-matchers.h
/usr/src/googletest/googletest/include/gtest/gtest-message.h
/usr/src/googletest/googletest/include/gtest/gtest-param-test.h
/usr/src/googletest/googletest/include/gtest/gtest-printers.h
/usr/src/googletest/googletest/include/gtest/gtest-spi.h
/usr/src/googletest/googletest/include/gtest/gtest-test-part.h
/usr/src/googletest/googletest/include/gtest/gtest-typed-test.h
/usr/src/googletest/googletest/include/gtest/gtest.h
/usr/src/googletest/googletest/include/gtest/gtest_pred_impl.h
/usr/src/googletest/googletest/include/gtest/gtest_prod.h
/usr/src/googletest/googletest/include/gtest/internal
/usr/src/googletest/googletest/include/gtest/internal/custom
/usr/src/googletest/googletest/include/gtest/internal/custom/README.md
/usr/src/googletest/googletest/include/gtest/internal/custom/gtest-port.h
/usr/src/googletest/googletest/include/gtest/internal/custom/gtest-printers.h
/usr/src/googletest/googletest/include/gtest/internal/custom/gtest.h
/usr/src/googletest/googletest/include/gtest/internal/gtest-death-test-internal.h
/usr/src/googletest/googletest/include/gtest/internal/gtest-filepath.h
/usr/src/googletest/googletest/include/gtest/internal/gtest-internal.h
/usr/src/googletest/googletest/include/gtest/internal/gtest-param-util.h
/usr/src/googletest/googletest/include/gtest/internal/gtest-port-arch.h
/usr/src/googletest/googletest/include/gtest/internal/gtest-port.h
/usr/src/googletest/googletest/include/gtest/internal/gtest-string.h
/usr/src/googletest/googletest/include/gtest/internal/gtest-type-util.h
/usr/src/googletest/googletest/include/gtest/internal/gtest-type-util.h.pump
/usr/src/googletest/googletest/samples
/usr/src/googletest/googletest/samples/prime_tables.h
/usr/src/googletest/googletest/samples/sample1.cc
/usr/src/googletest/googletest/samples/sample1.h
/usr/src/googletest/googletest/samples/sample10_unittest.cc
/usr/src/googletest/googletest/samples/sample1_unittest.cc
/usr/src/googletest/googletest/samples/sample2.cc
/usr/src/googletest/googletest/samples/sample2.h
/usr/src/googletest/googletest/samples/sample2_unittest.cc
/usr/src/googletest/googletest/samples/sample3-inl.h
/usr/src/googletest/googletest/samples/sample3_unittest.cc
/usr/src/googletest/googletest/samples/sample4.cc
/usr/src/googletest/googletest/samples/sample4.h
/usr/src/googletest/googletest/samples/sample4_unittest.cc
/usr/src/googletest/googletest/samples/sample5_unittest.cc
/usr/src/googletest/googletest/samples/sample6_unittest.cc
/usr/src/googletest/googletest/samples/sample7_unittest.cc
/usr/src/googletest/googletest/samples/sample8_unittest.cc
/usr/src/googletest/googletest/samples/sample9_unittest.cc
/usr/src/googletest/googletest/scripts
/usr/src/googletest/googletest/scripts/common.py
/usr/src/googletest/googletest/scripts/fuse_gtest_files.py
/usr/src/googletest/googletest/scripts/gen_gtest_pred_impl.py
/usr/src/googletest/googletest/scripts/gtest-config.in
/usr/src/googletest/googletest/scripts/pump.py
/usr/src/googletest/googletest/scripts/release_docs.py
/usr/src/googletest/googletest/scripts/test
/usr/src/googletest/googletest/scripts/test/Makefile
/usr/src/googletest/googletest/scripts/upload.py
/usr/src/googletest/googletest/scripts/upload_gtest.py
/usr/src/googletest/googletest/src
/usr/src/googletest/googletest/src/gtest-all.cc
/usr/src/googletest/googletest/src/gtest-death-test.cc
/usr/src/googletest/googletest/src/gtest-filepath.cc
/usr/src/googletest/googletest/src/gtest-internal-inl.h
/usr/src/googletest/googletest/src/gtest-matchers.cc
/usr/src/googletest/googletest/src/gtest-port.cc
/usr/src/googletest/googletest/src/gtest-printers.cc
/usr/src/googletest/googletest/src/gtest-test-part.cc
/usr/src/googletest/googletest/src/gtest-typed-test.cc
/usr/src/googletest/googletest/src/gtest.cc
/usr/src/googletest/googletest/src/gtest_main.cc
/usr/src/googletest/googletest/test
/usr/src/googletest/googletest/test/BUILD.bazel
/usr/src/googletest/googletest/test/googletest-break-on-failure-unittest.py
/usr/src/googletest/googletest/test/googletest-break-on-failure-unittest_.cc
/usr/src/googletest/googletest/test/googletest-catch-exceptions-test.py
/usr/src/googletest/googletest/test/googletest-catch-exceptions-test_.cc
/usr/src/googletest/googletest/test/googletest-color-test.py
/usr/src/googletest/googletest/test/googletest-color-test_.cc
/usr/src/googletest/googletest/test/googletest-death-test-test.cc
/usr/src/googletest/googletest/test/googletest-death-test_ex_test.cc
/usr/src/googletest/googletest/test/googletest-env-var-test.py
/usr/src/googletest/googletest/test/googletest-env-var-test_.cc
/usr/src/googletest/googletest/test/googletest-filepath-test.cc
/usr/src/googletest/googletest/test/googletest-filter-unittest.py
/usr/src/googletest/googletest/test/googletest-filter-unittest_.cc
/usr/src/googletest/googletest/test/googletest-json-outfiles-test.py
/usr/src/googletest/googletest/test/googletest-json-output-unittest.py
/usr/src/googletest/googletest/test/googletest-list-tests-unittest.py
/usr/src/googletest/googletest/test/googletest-list-tests-unittest_.cc
/usr/src/googletest/googletest/test/googletest-listener-test.cc
/usr/src/googletest/googletest/test/googletest-message-test.cc
/usr/src/googletest/googletest/test/googletest-options-test.cc
/usr/src/googletest/googletest/test/googletest-output-test-golden-lin.txt
/usr/src/googletest/googletest/test/googletest-output-test.py
/usr/src/googletest/googletest/test/googletest-output-test_.cc
/usr/src/googletest/googletest/test/googletest-param-test-invalid-name1-test.py
/usr/src/googletest/googletest/test/googletest-param-test-invalid-name1-test_.cc
/usr/src/googletest/googletest/test/googletest-param-test-invalid-name2-test.py
/usr/src/googletest/googletest/test/googletest-param-test-invalid-name2-test_.cc
/usr/src/googletest/googletest/test/googletest-param-test-test.cc
/usr/src/googletest/googletest/test/googletest-param-test-test.h
/usr/src/googletest/googletest/test/googletest-param-test2-test.cc
/usr/src/googletest/googletest/test/googletest-port-test.cc
/usr/src/googletest/googletest/test/googletest-printers-test.cc
/usr/src/googletest/googletest/test/googletest-shuffle-test.py
/usr/src/googletest/googletest/test/googletest-shuffle-test_.cc
/usr/src/googletest/googletest/test/googletest-test-part-test.cc
/usr/src/googletest/googletest/test/googletest-test2_test.cc
/usr/src/googletest/googletest/test/googletest-throw-on-failure-test.py
/usr/src/googletest/googletest/test/googletest-throw-on-failure-test_.cc
/usr/src/googletest/googletest/test/googletest-uninitialized-test.py
/usr/src/googletest/googletest/test/googletest-uninitialized-test_.cc
/usr/src/googletest/googletest/test/gtest-typed-test2_test.cc
/usr/src/googletest/googletest/test/gtest-typed-test_test.cc
/usr/src/googletest/googletest/test/gtest-typed-test_test.h
/usr/src/googletest/googletest/test/gtest-unittest-api_test.cc
/usr/src/googletest/googletest/test/gtest_all_test.cc
/usr/src/googletest/googletest/test/gtest_assert_by_exception_test.cc
/usr/src/googletest/googletest/test/gtest_environment_test.cc
/usr/src/googletest/googletest/test/gtest_help_test.py
/usr/src/googletest/googletest/test/gtest_help_test_.cc
/usr/src/googletest/googletest/test/gtest_json_test_utils.py
/usr/src/googletest/googletest/test/gtest_list_output_unittest.py
/usr/src/googletest/googletest/test/gtest_list_output_unittest_.cc
/usr/src/googletest/googletest/test/gtest_main_unittest.cc
/usr/src/googletest/googletest/test/gtest_no_test_unittest.cc
/usr/src/googletest/googletest/test/gtest_pred_impl_unittest.cc
/usr/src/googletest/googletest/test/gtest_premature_exit_test.cc
/usr/src/googletest/googletest/test/gtest_prod_test.cc
/usr/src/googletest/googletest/test/gtest_repeat_test.cc
/usr/src/googletest/googletest/test/gtest_skip_environment_check_output_test.py
/usr/src/googletest/googletest/test/gtest_skip_in_environment_setup_test.cc
/usr/src/googletest/googletest/test/gtest_skip_test.cc
/usr/src/googletest/googletest/test/gtest_sole_header_test.cc
/usr/src/googletest/googletest/test/gtest_stress_test.cc
/usr/src/googletest/googletest/test/gtest_test_macro_stack_footprint_test.cc
/usr/src/googletest/googletest/test/gtest_test_utils.py
/usr/src/googletest/googletest/test/gtest_testbridge_test.py
/usr/src/googletest/googletest/test/gtest_testbridge_test_.cc
/usr/src/googletest/googletest/test/gtest_throw_on_failure_ex_test.cc
/usr/src/googletest/googletest/test/gtest_unittest.cc
/usr/src/googletest/googletest/test/gtest_xml_outfile1_test_.cc
/usr/src/googletest/googletest/test/gtest_xml_outfile2_test_.cc
/usr/src/googletest/googletest/test/gtest_xml_outfiles_test.py
/usr/src/googletest/googletest/test/gtest_xml_output_unittest.py
/usr/src/googletest/googletest/test/gtest_xml_output_unittest_.cc
/usr/src/googletest/googletest/test/gtest_xml_test_utils.py
/usr/src/googletest/googletest/test/production.cc
/usr/src/googletest/googletest/test/production.h

files in package **googletest-tools**:
>/.
/usr
/usr/bin
/usr/bin/gmock_gen
/usr/share
/usr/share/doc
/usr/share/doc/googletest-tools
/usr/share/doc/googletest-tools/changelog.Debian.gz
/usr/share/doc/googletest-tools/copyright
/usr/share/googletest-tools
/usr/share/googletest-tools/generator
/usr/share/googletest-tools/generator/cpp
/usr/share/googletest-tools/generator/cpp/__init__.py
/usr/share/googletest-tools/generator/cpp/ast.py
/usr/share/googletest-tools/generator/cpp/gmock_class.py
/usr/share/googletest-tools/generator/cpp/gmock_class_test.py
/usr/share/googletest-tools/generator/cpp/keywords.py
/usr/share/googletest-tools/generator/cpp/tokenize.py
/usr/share/googletest-tools/generator/cpp/utils.py
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/gmock_gen.1.gz

files in package **google-mock**:
>/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/google-mock
/usr/share/doc/google-mock/changelog.Debian.gz
/usr/share/doc/google-mock/copyright
/usr/src
/usr/src/gmock

**Comment by lucky62** [comment]
SOLVED!

After a lot of install/deinstall/install - I found this:

Packages required to compile PLUG with UNITTEST=ON:

- googletests
- google-mock
- libgmock-dev
- libgtest-dev

Before each run of cmake I must clean the build directory, because the cmake is caching...

Result:
>$ rm -r ./*; cmake ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ~~~ plug v1.4.1 ~~~
-- Unit Tests : ON
-- Integrationtests : OFF
-- Coverage : OFF
-- LTO : OFF
-- ASan : OFF
-- UBSan : OFF
-- Build Type : None
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found libusb-1.0: /usr/lib/x86_64-linux-gnu/libusb-1.0.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found GTest: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /SHARED/SSD_DATA/plug/build
