### ISSUE TITLE
Compiling fails in Manjaro

### ISSUE THREAD

**Issue by Snayler** [offa/plug#5]
I'm trying to compile Plug 1.4.1 in Manjaro, but I'm getting the following error after running make:

> Scanning dependencies of target plug-updater
> [ 36%] Building CXX object src/com/CMakeFiles/plug-updater.dir/plug-updater_autogen/mocs_compilation.cpp.o
> [ 38%] Building CXX object src/com/CMakeFiles/plug-updater.dir/MustangUpdater.cpp.o
> In file included from /home/snayler/Downloads/plug-1.4.1/src/com/MustangUpdater.cpp:25:
> /home/snayler/Downloads/plug-1.4.1/include/com/Packet.h: In member function ‘plug::com::Type plug::com::Header::getType() const’:
> /home/snayler/Downloads/plug-1.4.1/include/com/Packet.h:140:32: error: ‘domain_error’ is not a member of ‘std’
>   140 |                     throw std::domain_error("Invalid Type: " + std::to_string(bytes[1]));
>       |                                ^~~~~~~~~~~~
> /home/snayler/Downloads/plug-1.4.1/include/com/Packet.h: In member function ‘plug::com::DSP plug::com::Header::getDSP() const’:
> /home/snayler/Downloads/plug-1.4.1/include/com/Packet.h:200:32: error: ‘domain_error’ is not a member of ‘std’
>   200 |                     throw std::domain_error("Invalid DSP: " + std::to_string(bytes[2]));
>       |                                ^~~~~~~~~~~~
> make[2]: *** [src/com/CMakeFiles/plug-updater.dir/build.make:95: src/com/CMakeFiles/plug-updater.dir/MustangUpdater.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:305: src/com/CMakeFiles/plug-updater.dir/all] Error 2
> make: *** [Makefile:160: all] Error 2

From the error, I can't find anything obvious, so I'd like to see if anyone would have a clue of what's wrong.

**Comment by offa** [comment]
Thanks for reporting, the issue should be fixed on *master* already. Can you verify this on your system?

**Comment by Snayler** [comment]
Thanks, it worked!

**Comment by offa** [comment]
I've released v1.4.2, which includes the fix.
