### ISSUE TITLE
Fender Mustang 2 - Core Dumped

### ISSUE THREAD

**Issue by mewt666** [offa/plug#8]
I have installed plug from the AUR and while the application will start when there is no amp connected, once connected the application will crash with the following:

[~]$ plug
/usr/include/c++/12.1.0/bits/stl_vector.h:1142: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](size_type) const [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >; const_reference = const std::__cxx11::basic_string<char>&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)

The amp appears to be well detected as per the following in dmesg: 

[   99.580968] usb 1-10: new full-speed USB device number 6 using xhci_hcd
[   99.888788] usb 1-10: New USB device found, idVendor=1ed8, idProduct=0004, bcdDevice= 1.00
[   99.888793] usb 1-10: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   99.888794] usb 1-10: Product: Mustang Amplifier
[   99.888795] usb 1-10: Manufacturer: FMIC
[   99.888796] usb 1-10: SerialNumber: 6FA6FF393638533243246843
[   99.907619] hid-generic 0003:1ED8:0004.0007: hiddev98,hidraw5: USB HID v1.10 Device [FMIC Mustang Amplifier] on usb-0000:03:00.0-10/input0

It is even detected by pipewire and detected as Mustang I/II.

**Comment by mewt666** [comment]
This is the package I installed:

https://aur.archlinux.org/packages/plug, which appears to build from this repository (url="https://github.com/offa/plug")

**Comment by offa** [comment]
There are many usb related changes since that version. You said building from source didn't cause the error? Did you use the 1.4.2 or master version?

**Comment by mewt666** [comment]
cloned master and just build using cmake and ran no issues

**Comment by offa** [comment]
Ok, thanks. I'm going to create a new release so packages can use the fixed version.
